# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=80)),
                ('download_url', models.CharField(max_length=300)),
                ('variable', models.CharField(max_length=80)),
                ('variable_long_name', models.CharField(max_length=80)),
                ('cf_standard_name', models.CharField(max_length=300)),
                ('data_node', models.URLField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='cmip5', max_length=80)),
                ('product', models.CharField(max_length=80)),
                ('institute', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('experiment', models.CharField(max_length=80)),
                ('frequency', models.CharField(max_length=80)),
                ('realm', models.CharField(max_length=80)),
                ('cmor_table', models.CharField(max_length=80)),
                ('ensemble', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=80)),
                ('experiment_family', models.CharField(max_length=80)),
                ('forcing', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset'),
        ),
    ]
