# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='dataset',
            new_name='dataset_id',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='id',
        ),
        migrations.AddField(
            model_name='datafile',
            name='tracking_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='variable_units',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafile',
            name='filename',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='forcing',
            field=models.CharField(max_length=500),
        ),
    ]
