# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0002_auto_20161212_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafile',
            name='dataset_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile'),
        ),
    ]
