# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='archive_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
