# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='esgf_ds_id',
            new_name='esgf_drs',
        ),
    ]
