# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='ceda_cc_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='cf_compliance_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_qc_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
