# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='up_to_date',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='up_to_date_note',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
