# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(default='', max_length=80)),
                ('variable', models.CharField(default='', max_length=20)),
                ('variable_long_name', models.CharField(default='', max_length=80)),
                ('cmor_table', models.CharField(default='', max_length=20)),
                ('frequency', models.CharField(default='', max_length=20)),
                ('priority', models.CharField(max_length=20, null=True)),
                ('number_experiments', models.PositiveSmallIntegerField(max_length=2, null=True)),
                ('number_ensemble_members', models.PositiveSmallIntegerField(max_length=2, null=True)),
                ('number_of_models', models.PositiveSmallIntegerField(default=0, max_length=2)),
                ('volume_of_data', models.PositiveSmallIntegerField(max_length=2, null=True)),
            ],
        ),
    ]
