# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='esgf_ds_id',
            new_name='esgf_drs',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='up_to_date_note',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.CharField(default='CMIP5', max_length=30),
        ),
    ]
