# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0002_auto_20170405_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='checksum',
            new_name='sha256_checksum',
        ),
    ]
