# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0002_auto_20171023_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.CharField(default='CMIP5', max_length=30),
        ),
    ]
