# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0002_datafile_archive_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspecification',
            name='data_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
