# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0002_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='number_ensemble_members',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='number_experiments',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='number_of_models',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requests',
            name='volume_of_data',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
