# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0003_datafile_qc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='qc',
            new_name='qc_passed',
        ),
    ]
