# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0003_auto_20170518_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='md5_checksum',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
