# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0003_auto_20170123_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
