# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0004_auto_20180328_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='published',
            field=models.NullBooleanField(default=None),
        ),
    ]
