# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0004_auto_20170217_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='size',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataspecification',
            name='data_volume',
            field=models.FloatField(blank=True),
        ),
    ]
