# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0004_auto_20170124_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cmor_table',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_models',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='request',
            name='variable',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='variable_long_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='request',
            name='volume_of_data',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
