# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0004_datafile_md5_checksum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qccheck',
            name='file_qc',
        ),
        migrations.AddField(
            model_name='qccheck',
            name='file_qc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile'),
        ),
    ]
