# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0005_auto_20170124_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='DataRequest',
        ),
    ]
