# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0005_auto_20170518_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcerror',
            name='qc_check',
        ),
        migrations.AddField(
            model_name='qccheck',
            name='qc_error',
            field=models.ManyToManyField(blank=True, null=True, to='qcapp.QCerror'),
        ),
    ]
