# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0005_datafile_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='gws_path',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
