# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0006_auto_20170217_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspecification',
            name='esgf_data_collected',
            field=models.BooleanField(default=False),
        ),
    ]
