# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0006_auto_20170124_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetQc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_axis', models.BooleanField()),
                ('time_axis_score', models.SmallIntegerField()),
                ('time_axis_details', models.CharField(max_length=500)),
                ('check_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='FileQc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_compilant', models.BooleanField()),
                ('cf_compliance_score', models.SmallIntegerField()),
                ('cf_compliance_details', models.CharField(max_length=500)),
                ('global_attributes', models.BooleanField()),
                ('global_attributes_score', models.SmallIntegerField()),
                ('global_attributes_details', models.CharField(max_length=500)),
                ('variable_attributes', models.BooleanField()),
                ('variable_attributes_score', models.SmallIntegerField()),
                ('variable_attributes_details', models.CharField(max_length=500)),
                ('check_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile')),
            ],
        ),
        migrations.AddField(
            model_name='datarequest',
            name='dataset_qc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQc'),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='file_qc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.FileQc'),
        ),
    ]
