# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0006_datafile_gws_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='restricted',
            field=models.NullBooleanField(default=None),
        ),
    ]
