# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0007_auto_20170130_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasetqc',
            name='check_dataset',
        ),
        migrations.RemoveField(
            model_name='fileqc',
            name='check_file',
        ),
        migrations.RenameField(
            model_name='datarequest',
            old_name='request_name',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='dataset_qc',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='file_qc',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='number_ensemble_members',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='number_experiments',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='number_of_models',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='volume_of_data',
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='DatasetQc',
        ),
        migrations.DeleteModel(
            name='FileQc',
        ),
    ]
