# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0007_dataspecification_esgf_data_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='data_node',
        ),
        migrations.AddField(
            model_name='dataset',
            name='esgf_ds_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dataset',
            name='esgf_node',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
