# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0007_remove_datafile_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qccheck',
            name='file_qc',
        ),
        migrations.RemoveField(
            model_name='qccheck',
            name='qc_error',
        ),
        migrations.RemoveField(
            model_name='qcerror',
            name='qc_error',
        ),
        migrations.AddField(
            model_name='qcerror',
            name='check_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qcerror',
            name='error_msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qcerror',
            name='error_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qcerror',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile'),
        ),
        migrations.AddField(
            model_name='qcerror',
            name='report_filepath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='QCcheck',
        ),
    ]
