# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0008_auto_20170613_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='timeseries',
            field=models.BooleanField(default=False),
        ),
    ]
