# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0009_datafile_timeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='ncfile',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
