# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0009_qcerror_error_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile'),
        ),
    ]
