# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0009_auto_20170202_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('experiment', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('cmor_table', models.CharField(max_length=20)),
                ('ensemble', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('experiment_family', models.CharField(blank=True, max_length=100)),
                ('forcing', models.CharField(blank=True, max_length=500)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('variable', models.CharField(max_length=20)),
                ('dataset_id', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dataspecification',
            name='requester',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_spec',
            field=models.ManyToManyField(blank=True, to='qcapp.DataSpecification'),
        ),
    ]
