# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0010_auto_20170202_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=300, unique=True)),
                ('size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=80)),
                ('tracking_id', models.CharField(max_length=80)),
                ('download_url', models.CharField(max_length=300)),
                ('variable', models.CharField(max_length=20)),
                ('variable_long_name', models.CharField(max_length=80)),
                ('cf_standard_name', models.CharField(max_length=300)),
                ('variable_units', models.CharField(max_length=20)),
                ('data_node', models.URLField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
            ],
        ),
    ]
