# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0010_datafile_ncfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='replica',
            field=models.NullBooleanField(default=None),
        ),
    ]
