# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0011_datafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_check_type', models.CharField(max_length=300)),
                ('qc_check_file', models.BooleanField(default=False)),
                ('qc_check_dataset', models.BooleanField(default=False)),
                ('qc_score', models.PositiveSmallIntegerField()),
                ('qc_details', models.TextField()),
            ],
        ),
    ]
