# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0012_remove_datafile_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='uptodate',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='uptodate',
            field=models.NullBooleanField(default=None),
        ),
    ]
