# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0012_qccheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileQc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_compliance_score', models.PositiveSmallIntegerField()),
                ('ceda_cc_score', models.PositiveSmallIntegerField()),
                ('check_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile')),
                ('qc_check', models.ManyToManyField(blank=True, to='qcapp.QCcheck')),
            ],
        ),
    ]
