# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0013_auto_20170320_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetqc',
            name='check_dataset',
        ),
        migrations.RemoveField(
            model_name='datasetqc',
            name='qc_check',
        ),
        migrations.RemoveField(
            model_name='qcpercentiles',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='qcpercentiles',
            name='qc_plot',
        ),
        migrations.RemoveField(
            model_name='qcplot',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='qcplot',
            name='qc_percentiles',
        ),
        migrations.RemoveField(
            model_name='qcresults',
            name='dataset_qc',
        ),
        migrations.RemoveField(
            model_name='qcresults',
            name='file_qc',
        ),
        migrations.RemoveField(
            model_name='fileqc',
            name='qc_check',
        ),
        migrations.RemoveField(
            model_name='qccheck',
            name='file_qc',
        ),
        migrations.AddField(
            model_name='qccheck',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.FileQC'),
        ),
        migrations.AlterField(
            model_name='qccheck',
            name='qc_check_type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='DatasetQC',
        ),
        migrations.DeleteModel(
            name='QCpercentiles',
        ),
        migrations.DeleteModel(
            name='QCplot',
        ),
        migrations.DeleteModel(
            name='QCresults',
        ),
    ]
