# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0014_dataset_supersedes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='new_version',
            new_name='new_dataset_version',
        ),
    ]
