# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0014_datasetqc_qcpercentiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCplot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, unique=True)),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('experiment', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('cmor_table', models.CharField(max_length=20)),
                ('ensemble', models.CharField(max_length=10)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('variable', models.CharField(max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
                ('qc_percentiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.QCpercentiles')),
            ],
        ),
    ]
