# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0014_auto_20171011_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='up_to_date_note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
