# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0015_auto_20170328_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetqc',
            name='check_dataset',
        ),
        migrations.RemoveField(
            model_name='datasetqc',
            name='qc_check',
        ),
        migrations.RemoveField(
            model_name='qcpercentiles',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='qcpercentiles',
            name='qc_plot',
        ),
        migrations.RemoveField(
            model_name='qcplot',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='qcplot',
            name='qc_percentiles',
        ),
        migrations.RemoveField(
            model_name='qcresults',
            name='dataset_qc',
        ),
        migrations.RemoveField(
            model_name='qcresults',
            name='file_qc',
        ),
        migrations.DeleteModel(
            name='DatasetQC',
        ),
        migrations.DeleteModel(
            name='QCpercentiles',
        ),
        migrations.DeleteModel(
            name='QCplot',
        ),
        migrations.DeleteModel(
            name='QCresults',
        ),
    ]
