# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0015_auto_20171011_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='uptodate',
            new_name='up_to_date',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='up_to_date',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='up_to_date_note',
        ),
        migrations.AddField(
            model_name='datafile',
            name='up_to_date_note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
