# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0016_auto_20180517_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcerror',
            name='check_performed',
            field=models.NullBooleanField(default=False),
        ),
    ]
