# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0016_qcpercentiles_qc_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC')),
                ('file_qc', models.ManyToManyField(to='qcapp.FileQC')),
            ],
        ),
    ]
