# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0017_qcerror_check_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcerror',
            name='check_performed',
        ),
    ]
