# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0017_auto_20170330_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='ceda_cc_score',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='cf_compliance_score',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='file_qc_score',
        ),
    ]
