# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0018_auto_20170330_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='ceda_cc_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='cf_compliance_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_qc_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
