# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0019_auto_20170330_1356'),
        ('qcapp', '0014_auto_20170327_0949'),
    ]

    operations = [
    ]
