# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0019_dataset_qc_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcerror',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset'),
        ),
    ]
