# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0021_auto_20170208_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='filename',
            new_name='filepath',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='experiment_family',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='forcing',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='dataset_qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.FileQC'),
        ),
    ]
