# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0021_dataset_is_timeseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='duplicate_of',
        ),
    ]
