# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0022_remove_datafile_duplicate_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='supersedes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superseded_by', to='qcapp.DataFile'),
        ),
    ]
