# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0024_auto_20181025_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcerror',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qcerror',
            name='report_filepath',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
