# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0025_auto_20170213_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=20)),
                ('variable_long_name', models.CharField(max_length=80)),
                ('cmor_table', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('priority', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='cmor_table',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='dataset_qc',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='file_qc',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='variable_long_name',
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='dataset_qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.FileQC'),
        ),
        migrations.AddField(
            model_name='requester',
            name='data_requester',
            field=models.ManyToManyField(to='qcapp.DataSpecification'),
        ),
        migrations.AddField(
            model_name='dataspecs',
            name='data_specs',
            field=models.ManyToManyField(to='qcapp.DataSpecification'),
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='requested_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='qcapp.Requester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='specs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataSpecs'),
            preserve_default=False,
        ),
    ]
