# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0026_auto_20181113_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcerror',
            name='error_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
