# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0030_auto_20170215_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataspecs',
            name='data_specs',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='specs',
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='cmor_table',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='frequency',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='priority',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='variable',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='variable_long_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='dataspecification',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataRequester'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='dataset_qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.FileQC'),
        ),
        migrations.DeleteModel(
            name='DataSpecs',
        ),
    ]
