# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0030_datafile_qc_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='published',
            field=models.NullBooleanField(default=False),
        ),
    ]
