# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0031_auto_20190116_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='published',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='published',
            field=models.NullBooleanField(default=None),
        ),
    ]
