# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0032_auto_20170215_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequester',
            name='data_specs',
        ),
        migrations.RemoveField(
            model_name='dataspecification',
            name='req',
        ),
        migrations.AddField(
            model_name='dataspecification',
            name='requester',
            field=models.ManyToManyField(blank=True, null=True, to='qcapp.DataRequester'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='dataset_qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.FileQC'),
        ),
    ]
