# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0039_auto_20170215_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='filepath',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='dataset_qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC'),
        ),
        migrations.AlterField(
            model_name='qcresults',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.FileQC'),
        ),
    ]
