# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=300)),
                ('size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=80)),
                ('tracking_id', models.CharField(blank=True, max_length=80)),
                ('download_url', models.CharField(max_length=300)),
                ('variable', models.CharField(max_length=20)),
                ('variable_long_name', models.CharField(max_length=80)),
                ('cf_standard_name', models.CharField(max_length=300)),
                ('variable_units', models.CharField(max_length=20)),
                ('data_node', models.URLField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DataRequester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=False)),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('experiment', models.CharField(blank=True, max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=20)),
                ('realm', models.CharField(blank=True, max_length=20)),
                ('cmor_table', models.CharField(blank=True, max_length=20)),
                ('ensemble', models.CharField(blank=True, max_length=10)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('variable', models.CharField(blank=True, max_length=20)),
                ('dataset_id', models.CharField(blank=True, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_score_of_ds_files', models.SmallIntegerField()),
                ('check_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DataSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=20)),
                ('variable_long_name', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('cmor_table', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('number_of_models', models.IntegerField(default=0)),
                ('datarequesters', models.ManyToManyField(blank=True, to='qcapp.DataRequester')),
            ],
        ),
        migrations.CreateModel(
            name='FileQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_compliance_score', models.PositiveSmallIntegerField(default=0)),
                ('ceda_cc_score', models.PositiveSmallIntegerField(default=0)),
                ('file_qc_score', models.PositiveSmallIntegerField(default=0)),
                ('check_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DataFile')),
            ],
        ),
        migrations.CreateModel(
            name='QCcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_check_type', models.CharField(max_length=300)),
                ('qc_check_file', models.BooleanField(default=False)),
                ('qc_check_dataset', models.BooleanField(default=False)),
                ('qc_score', models.PositiveSmallIntegerField()),
                ('qc_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QCpercentiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('experiment', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('cmor_table', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ensemble', models.CharField(max_length=10)),
                ('variable', models.CharField(max_length=20)),
                ('max_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p999_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p990_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p950_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p750_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p500_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p250_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p050_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p010_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p001_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('min_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('ma_max_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('ma_min_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='QCplot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, unique=True)),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('experiment', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('cmor_table', models.CharField(max_length=20)),
                ('ensemble', models.CharField(max_length=10)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('variable', models.CharField(max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
                ('qc_percentiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.QCpercentiles')),
            ],
        ),
        migrations.CreateModel(
            name='QCresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC')),
                ('file_qc', models.ManyToManyField(to='qcapp.FileQC')),
            ],
        ),
        migrations.AddField(
            model_name='qcpercentiles',
            name='qc_plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.QCplot'),
        ),
        migrations.AddField(
            model_name='fileqc',
            name='qc_check',
            field=models.ManyToManyField(blank=True, to='qcapp.QCcheck'),
        ),
        migrations.AddField(
            model_name='datasetqc',
            name='qc_check',
            field=models.ManyToManyField(blank=True, to='qcapp.QCcheck'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_spec',
            field=models.ManyToManyField(blank=True, to='qcapp.DataSpecification'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset'),
        ),
    ]
