# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0008_auto_20170222_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='cmor_table',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_id',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='ensemble',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='experiment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='institute',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='product',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='realm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='variable',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
