# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0009_auto_20170222_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_result', models.CharField(blank=True, max_length=500)),
                ('qc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.FileQC')),
            ],
        ),
    ]
