# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0011_auto_20170320_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccheck',
            name='file_qc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='qcapp.FileQC'),
            preserve_default=False,
        ),
    ]
