# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0014_auto_20170328_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_score_of_ds_files', models.SmallIntegerField()),
                ('check_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
                ('qc_check', models.ManyToManyField(blank=True, to='qcapp.QCcheck')),
            ],
        ),
        migrations.CreateModel(
            name='QCpercentiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('experiment', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('cmor_table', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ensemble', models.CharField(max_length=10)),
                ('variable', models.CharField(max_length=20)),
                ('max_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p999_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p990_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p950_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p750_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p500_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p250_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p050_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p010_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p001_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('min_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('ma_max_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('ma_min_value', models.DecimalField(decimal_places=1, max_digits=8)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='QCplot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, unique=True)),
                ('project', models.CharField(default='cmip5', max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('experiment', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('cmor_table', models.CharField(max_length=20)),
                ('ensemble', models.CharField(max_length=10)),
                ('start_time', models.DateField(blank=True)),
                ('end_time', models.DateField(blank=True)),
                ('variable', models.CharField(max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.Dataset')),
                ('qc_percentiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.QCpercentiles')),
            ],
        ),
        migrations.CreateModel(
            name='QCresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcapp.DatasetQC')),
                ('file_qc', models.ManyToManyField(to='qcapp.FileQC')),
            ],
        ),
        migrations.AddField(
            model_name='qcpercentiles',
            name='qc_plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qcapp.QCplot'),
        ),
    ]
