# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcapp', '0016_auto_20170328_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileqc',
            name='check_file',
        ),
        migrations.AddField(
            model_name='datafile',
            name='ceda_cc_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='cf_compliance_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_qc_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qccheck',
            name='file_qc',
            field=models.ManyToManyField(to='qcapp.DataFile'),
        ),
        migrations.DeleteModel(
            name='FileQC',
        ),
    ]
